integrations:
  github:
    - host: github.com
      # It's highly recommended to use an environment variable for the token:
      token: "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"
      # OR, for testing, you can put the token directly (less secure):
      # token: "ghp_YOUR_GENERATED_GITHUB_PAT_HERE"
